[package]
name = "days"
version = "0.1.0"
authors = [ "Rain <kitgxrl@protonmail.com" ]
homepage = "https://github.com/kitgxrl/days"
repository = "https://github.com/kitgxrl/days"
edition = "2021"

[dependencies]
env_logger = "*"
log = "*"
clap = "*"
